[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["versionhq"]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "versionHQ.__version__"}

[project]
name = "versionHQ"
version = "1.1.1"
authors = [{ name = "Kuriko Iwai", email = "kuriko@versi0n.io" }]
description = "Orchestration frameworks for model-agnostic AI agents that handle outbound efforts"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
keywords = ["orchestration framework", "orchestration", "ai agent", "multi-agent system", "RAG", "agent", "version"]
dependencies = [
  "regex>=2024.11.6",
  "requests>=2.32.3",
  "pydantic>=2.9.2",
  "werkzeug>=3.1.3",
  "typing",
  "json-repair>=0.31.0",
  "litellm>=1.55.8",
  "openai>=1.57.0",
  "composio-openai>=0.6.0",
  "pre-commit>=4.0.1",
  "gunicorn>=23.0.0",
  "composio>=0.1.0",
  "setuptools>=75.6.0",
  "wheel>=0.45.1",
]
classifiers = [
  "Programming Language :: Python",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://versi0n.io"
Repository = "https://github.com/versionHQ/multi-agent-system"
Issues = "https://github.com/versionHQ/multi-agent-system/issues"

[tool.uv]
dev-dependencies = [
  "mypy>=1.10.0",
  "pre-commit>=3.6.0",
  "pytest>=8.0.0",
  "pytest-vcr>=1.0.2",
  "python-dotenv>=1.0.0",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.uv.workspace]
members = ["krik8235"]

[tool.mypy]
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = [""]
