name: Test-PyPi Publisher

on: push

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.11"

    - name: Build release distributions
      run: |
        uv venv --python=python3.13.1
        source .venv/bin/activate
        uv pip install --upgrade pip twine black
        uv pip install -r requirements.txt
        rm -rf dist
        uv build --sdist --wheel
      
    - name: Retrieve release distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPi
    needs:
    - build
    runs-on: ubuntu-lates

    environment:
      name: testpypi
      url: https://test.pypi.org/p/versionhq

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish to TestPyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
