name: Publisher

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.11"

    - name: Build release distributions
      run: |
        uv venv --python=python3.13.1
        source .venv/bin/activate
        uv pip install --upgrade pip twine black
        uv pip install -r requirements.txt
        rm -rf dist
        uv build --sdist --wheel

    - name: Retrieve release distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
    - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/versionhq
